[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "RainDataChecks"
authors = [{name = "Tim Kerr", email = "Tim.Kerr@Rainfall.NZ"}]
dynamic = ["version", "description"]
